
services:
  portfolio.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=10000
      - HostAPI=portfolio.api:11000
      - HostIdentity=portfolio.identity:12000
    ports:
      - "10000:10000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  portfolio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=11000
      - DBHost=db.api
      - DBDatabase=portfolio.api
    ports:
      - "11000:11000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  portfolio.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=12000
      - DBHost=db.identity
      - DBDatabase=portfolio.identity
      - HostIdentity=portfolio.identity:12000
    ports:
      - "12000:12000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db.api:
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: portfolio.api
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  db.identity:
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: portfolio.identity
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql