
services:
  gateway.portfolio:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "80:80"
  frontend.portfolio:
    ports:
      - "10000:80"
  api.portfolio:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=80
      - DBHost=db.api.portfolio
      - RedisCache=cache
    ports:
      - "11000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  id.portfolio:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=80
      - DBHost=db.id.portfolio
    ports:
      - "12000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db.api.portfolio:
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: portfolio.api
    ports:
      - "3307:3306"
    volumes:
      - api_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 0s
      start_interval: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  db.id.portfolio:
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: portfolio.identity
    ports:
      - "3308:3306"
    volumes:
      - id_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 0s
      start_interval: 5s
      interval: 5s
      timeout: 5s
      retries: 3
  cache:
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      start_period: 0s
      start_interval: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  s3.portfolio:
    command: server /data --console-address ":9001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
volumes:
  s3_data:
  id_db:
  api_db:  