services:
  portfolio.frontend:
    image: ${DOCKER_REGISTRY-}portfoliofrontend
    build:
      context: .
      dockerfile: PortfolioSite/Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"