services:
  gateway.portfolio:
    image: ${DOCKER_REGISTRY-}gateway.portfolio
    build:
      context: .
      dockerfile: Portfolio.Gateway/Dockerfile
    depends_on:
      - api.portfolio
      - id.portfolio
  frontend.portfolio:
    image: ${DOCKER_REGISTRY-}frontend.portfolio
    build:
      context: .
      dockerfile: Portfolio.Frontend/Dockerfile
    depends_on:
      - api.portfolio
      - id.portfolio
  api.portfolio:
    image: ${DOCKER_REGISTRY-}api.portfolio
    build:
      context: .
      dockerfile: Portfolio.API/Dockerfile
    depends_on:
      db.api.portfolio:
        condition: service_healthy
      cache:
        condition: service_healthy
  id.portfolio:
    image: ${DOCKER_REGISTRY-}id.portfolio
    build:
      context: .
      dockerfile: Portfolio.Identity/Dockerfile
    depends_on:
      db.id.portfolio:
        condition: service_healthy
  db.api.portfolio:
    image: mysql:9.2
    restart: always
  db.id.portfolio:
    image: mysql:9.2
    restart: always
  cache:
    image: redis:latest
    restart: always