services:
  portfolio.frontend:
    image: ${DOCKER_REGISTRY-}portfoliofrontend
    build:
      context: .
      dockerfile: PortfolioSite/Dockerfile
  portfolio.api:
    image: ${DOCKER_REGISTRY-}portfolioapi
    build:
      context: .
      dockerfile: Portfolio.API/Dockerfile
  portfolio.identity:
    image: ${DOCKER_REGISTRY-}portfolioidentity
    build:
      context: .
      dockerfile: Portfolio.Identity/Dockerfile
  db.api:
    image: mysql:latest
    restart: always
  db.identity:
    image: mysql:latest
    restart: always