<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.3.efcore.9.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Portfolio.Infrastructure\Portfolio.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Localization\ValidationFields.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ValidationFields.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\ValidationFields.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ValidationFields.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
