<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
	<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <UserSecretsId>52cf250e-bc24-4e33-89ca-ad0e3f395530</UserSecretsId>
	<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Resources\Pages\Dean.ru.resx" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Dockerfile" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\Pages\Dean.ru.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Blazorise" Version="1.7.5" />
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.7.5" />
    <PackageReference Include="Blazorise.Components" Version="1.7.5" />
    <PackageReference Include="Blazorise.DataGrid" Version="1.7.5" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.7.5" />
    <PackageReference Include="Blazorise.Sidebar" Version="1.7.5" />
    <PackageReference Include="Blazorise.Snackbar" Version="1.7.5" />
    <PackageReference Include="BlazorPro.BlazorSize" Version="9.0.0" />
    <PackageReference Include="Duende.IdentityModel" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Portfolio.Application\Portfolio.Application.csproj" />
  </ItemGroup>

</Project>
