@PortfolioServer_HostAddress = https://localhost:6001

POST {{PortfolioServer_HostAddress}}/discipline/Add?name=string

###

DELETE {{PortfolioServer_HostAddress}}/discipline/DeleteById?id=0

###

GET {{PortfolioServer_HostAddress}}/discipline/Get

###
